spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tech #jdbc:oracle:thin:@192.168.0.133:1521/XE
    username: prithwi
    password: capgemini
    driver-class-name: com.mysql.cj.jdbc.Driver  #oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8085/eureka
